import {
  AccessibilityIcon,
  AArrowDownIcon,
  AArrowUpIcon,
  AirplayIcon,
  AudioLinesIcon,
  CaptionsIcon,
  CaptionsOffIcon,
  CastIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  DownloadIcon,
  FastForwardIcon,
  GaugeIcon,
  ListVideoIcon,
  MaximizeIcon,
  MinimizeIcon,
  MinusIcon,
  MonitorDownIcon,
  MonitorUpIcon,
  PauseIcon,
  PictureInPicture2Icon,
  PictureInPictureIcon,
  PlayIcon,
  PlusIcon,
  RewindIcon,
  RotateCcwIcon,
  SettingsIcon,
  Volume1Icon,
  Volume2Icon,
  VolumeXIcon,
} from "lucide-react";
import type { DefaultLayoutIcons } from "@vidstack/react/player/layouts/default";

export const videoIcons = {
  AirPlayButton: { Default: AirplayIcon },
  GoogleCastButton: { Default: CastIcon },
  PlayButton: {
    Play: PlayIcon,
    Pause: PauseIcon,
    Replay: RotateCcwIcon,
  },
  MuteButton: {
    Mute: VolumeXIcon,
    VolumeLow: Volume1Icon,
    VolumeHigh: Volume2Icon,
  },
  CaptionButton: {
    On: CaptionsIcon,
    Off: CaptionsOffIcon,
  },
  PIPButton: {
    Enter: PictureInPicture2Icon,
    Exit: PictureInPictureIcon,
  },
  FullscreenButton: {
    Enter: MaximizeIcon,
    Exit: MinimizeIcon,
  },
  SeekButton: {
    Backward: RewindIcon,
    Forward: FastForwardIcon,
  },
  DownloadButton: { Default: DownloadIcon },
  Menu: {
    Accessibility: AccessibilityIcon,
    ArrowLeft: ChevronLeftIcon,
    ArrowRight: ChevronRightIcon,
    Audio: AudioLinesIcon,
    AudioBoostUp: PlusIcon,
    AudioBoostDown: MinusIcon,
    Chapters: ListVideoIcon,
    Captions: CaptionsIcon,
    Playback: GaugeIcon,
    Settings: SettingsIcon,
    SpeedUp: PlusIcon,
    SpeedDown: MinusIcon,
    QualityUp: MonitorUpIcon,
    QualityDown: MonitorDownIcon,
    FontSizeUp: AArrowUpIcon,
    FontSizeDown: AArrowDownIcon,
    OpacityUp: PlusIcon,
    OpacityDown: MinusIcon,
    RadioCheck: CheckIcon,
  },
  KeyboardDisplay: {
    Play: PlayIcon,
    Pause: PauseIcon,
    Mute: VolumeXIcon,
    VolumeUp: Volume2Icon,
    VolumeDown: Volume1Icon,
    EnterFullscreen: MaximizeIcon,
    ExitFullscreen: MinimizeIcon,
    EnterPiP: PictureInPicture2Icon,
    ExitPiP: PictureInPictureIcon,
    CaptionsOn: CaptionsIcon,
    CaptionsOff: CaptionsOffIcon,
    SeekForward: FastForwardIcon,
    SeekBackward: RewindIcon,
  },
} satisfies DefaultLayoutIcons;
